# Site settings
title: Blog de Florian Paquet
email: contact@florianpaquet.com
description: >-
  Un blog qui peut parfois être sérieux, et parfois non. Un peu comme nous tous en fait.
baseurl: ""
url: ""
excerpt_separator: <!--more-->
twitter_username:
github_username:  florianpaquet
minima:
  date_format: "%d %B %Y - %H:%m"
disqus:
  shortname: florian-paquet
lang: fr

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
